<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ur5">
  <!-- Common properties -->
  
  <!-- UR5 specific properties -->
  <xacro:property name="shoulder_height" value="0.089159" />
  <xacro:property name="shoulder_offset" value="0.13585" />
  <xacro:property name="upper_arm_length" value="0.425" />
  <xacro:property name="forearm_length" value="0.39225" />
  <xacro:property name="wrist_1_length" value="0.09465" />
  <xacro:property name="wrist_2_length" value="0.09465" />
  <xacro:property name="wrist_3_length" value="0.0823" />
  
  <!-- Materials -->
  <material name="ur_grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>
  
  <material name="ur_blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  
  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.06"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.025"/>
      <material name="ur_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.06"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.025"/>
    </collision>
    <inertial>
      <mass value="4.0"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00443333156" ixy="0.0" ixz="0.0" iyy="0.00443333156" iyz="0.0" izz="0.0072"/>
    </inertial>
  </link>
  
  <!-- Shoulder Link -->
  <joint name="shoulder_pan_joint" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${shoulder_height}"/>
    <axis xyz="0 0 1"/>
    <limit effort="150.0" lower="${-2*pi}" upper="${2*pi}" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="shoulder_link">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.06"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="ur_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.06"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="3.7"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.010267495893" ixy="0.0" ixz="0.0" iyy="0.010267495893" iyz="0.0" izz="0.00666"/>
    </inertial>
  </link>
  
  <!-- Upper Arm Link -->
  <joint name="shoulder_lift_joint" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm_link"/>
    <origin rpy="0 ${pi/2} 0" xyz="0 ${shoulder_offset} 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="150.0" lower="${-2*pi}" upper="${2*pi}" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="upper_arm_link">
    <visual>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="0.05"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${upper_arm_length/2} 0 0"/>
      <material name="ur_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="0.05"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${upper_arm_length/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="8.393"/>
      <origin rpy="0 0 0" xyz="${upper_arm_length/2} 0 0"/>
      <inertia ixx="0.22689067591" ixy="0.0" ixz="0.0" iyy="0.22689067591" iyz="0.0" izz="0.0151074"/>
    </inertial>
  </link>
  
  <!-- Forearm Link -->
  <joint name="elbow_joint" type="revolute">
    <parent link="upper_arm_link"/>
    <child link="forearm_link"/>
    <origin rpy="0 0 0" xyz="${upper_arm_length} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="150.0" lower="${-2*pi}" upper="${2*pi}" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="forearm_link">
    <visual>
      <geometry>
        <cylinder length="${forearm_length}" radius="0.04"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${forearm_length/2} 0 0"/>
      <material name="ur_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${forearm_length}" radius="0.04"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${forearm_length/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="2.275"/>
      <origin rpy="0 0 0" xyz="${forearm_length/2} 0 0"/>
      <inertia ixx="0.049443313556" ixy="0.0" ixz="0.0" iyy="0.049443313556" iyz="0.0" izz="0.00364"/>
    </inertial>
  </link>
  
  <!-- Wrist 1 Link -->
  <joint name="wrist_1_joint" type="revolute">
    <parent link="forearm_link"/>
    <child link="wrist_1_link"/>
    <origin rpy="0 0 0" xyz="${forearm_length} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="28.0" lower="${-2*pi}" upper="${2*pi}" velocity="3.2"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="wrist_1_link">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.035"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="0 0 ${wrist_1_length/2}"/>
      <material name="ur_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.035"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="0 0 ${wrist_1_length/2}"/>
    </collision>
    <inertial>
      <mass value="1.219"/>
      <origin rpy="0 0 0" xyz="0 0 ${wrist_1_length/2}"/>
      <inertia ixx="0.111172755531" ixy="0.0" ixz="0.0" iyy="0.111172755531" iyz="0.0" izz="0.21942"/>
    </inertial>
  </link>
  
  <!-- Wrist 2 Link -->
  <joint name="wrist_2_joint" type="revolute">
    <parent link="wrist_1_link"/>
    <child link="wrist_2_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${wrist_1_length}"/>
    <axis xyz="0 0 1"/>
    <limit effort="28.0" lower="${-2*pi}" upper="${2*pi}" velocity="3.2"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="wrist_2_link">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.035"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 ${-wrist_2_length/2} 0"/>
      <material name="ur_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.035"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 ${-wrist_2_length/2} 0"/>
    </collision>
    <inertial>
      <mass value="1.219"/>
      <origin rpy="0 0 0" xyz="0 ${-wrist_2_length/2} 0"/>
      <inertia ixx="0.111172755531" ixy="0.0" ixz="0.0" iyy="0.111172755531" iyz="0.0" izz="0.21942"/>
    </inertial>
  </link>
  
  <!-- Wrist 3 Link -->
  <joint name="wrist_3_joint" type="revolute">
    <parent link="wrist_2_link"/>
    <child link="wrist_3_link"/>
    <origin rpy="0 0 0" xyz="0 ${-wrist_2_length} 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="28.0" lower="${-2*pi}" upper="${2*pi}" velocity="3.2"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="wrist_3_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.035"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-wrist_3_length/2}"/>
      <material name="ur_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.035"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-wrist_3_length/2}"/>
    </collision>
    <inertial>
      <mass value="0.1879"/>
      <origin rpy="0 0 0" xyz="0 0 ${-wrist_3_length/2}"/>
      <inertia ixx="0.0171364731454" ixy="0.0" ixz="0.0" iyy="0.0171364731454" iyz="0.0" izz="0.033822"/>
    </inertial>
  </link>
  
  <!-- End Effector Link -->
  <joint name="ee_fixed_joint" type="fixed">
    <parent link="wrist_3_link"/>
    <child link="ee_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${-wrist_3_length}"/>
  </joint>
  
  <link name="ee_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="ur_blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  
  <!-- Tool0 Link -->
  <joint name="tool0_joint" type="fixed">
    <parent link="ee_link"/>
    <child link="tool0"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>
  
  <link name="tool0">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="ur_grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  
  <!-- Transmissions for ROS Control -->
  <transmission name="shoulder_pan_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_pan_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_pan_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="shoulder_lift_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_lift_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="shoulder_lift_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="elbow_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="elbow_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="wrist_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_1_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_1_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="wrist_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_2_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_2_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="wrist_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wrist_3_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="wrist_3_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <!-- Gazebo specific elements -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/ur5</robotNamespace>
    </plugin>
  </gazebo>
  
  <!-- Define colors for Gazebo -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="shoulder_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="upper_arm_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="forearm_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="wrist_1_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="wrist_2_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="wrist_3_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="ee_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="tool0">
    <material>Gazebo/Grey</material>
  </gazebo>
</robot>
