# Object detection configuration for ONNX models

object_detection:
  model:
    path: "/home/ubuntu/ros2_apm_fmm_ws/install/apm_core/share/apm_core/models/ssd_mobilenet_v2.onnx"
    input_name: "input_tensor"
    output_names: ["detection_boxes", "detection_scores", "detection_classes"]
    input_size: [320, 320]
    confidence_threshold: 0.5
    
  classes:
    path: "/home/ubuntu/ros2_apm_fmm_ws/install/apm_core/share/apm_core/config/coco_classes.txt"
    
  processing:
    enable_gpu: false
    execution_provider: "CPUExecutionProvider"
    max_detections: 10
    
  camera:
    topic: "/camera/color/image_raw"
    depth_topic: "/camera/depth/image_rect_raw"
    camera_info_topic: "/camera/color/camera_info"
    
  output:
    publish_visualization: true
    visualization_topic: "/apm/detection/visualization"
    detections_topic: "/apm/detection/detections"
    detected_objects_topic: "/apm/detection/objects"
