<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_robot">

  <!-- Constants for robot dimensions -->
  <xacro:property name="base_radius" value="0.2" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="upper_arm_length" value="0.25" />
  <xacro:property name="lower_arm_length" value="0.45" />
  <xacro:property name="platform_radius" value="0.1" />
  <xacro:property name="platform_height" value="0.02" />
  <xacro:property name="joint_radius" value="0.025" />
  
  <!-- Materials -->
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- World frame -->
  <link name="world"/>
  <joint name="world_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Macro for creating the upper arm -->
  <xacro:macro name="upper_arm" params="id angle">
    <link name="upper_arm_${id}">
      <visual>
        <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${upper_arm_length} 0.05 0.05"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${upper_arm_length} 0.05 0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
    </link>

    <joint name="base_to_upper_arm_${id}" type="revolute">
      <parent link="base_link"/>
      <child link="upper_arm_${id}"/>
      <origin xyz="${base_radius * cos(angle)} ${base_radius * sin(angle)} ${base_height}" rpy="0 0 ${angle}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
    </joint>

    <link name="upper_joint_${id}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="upper_arm_to_joint_${id}" type="fixed">
      <parent link="upper_arm_${id}"/>
      <child link="upper_joint_${id}"/>
      <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Macro for creating the lower arm -->
  <xacro:macro name="lower_arm" params="id angle">
    <link name="lower_arm_${id}">
      <visual>
        <origin xyz="0 0 -${lower_arm_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.02" length="${lower_arm_length}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 -${lower_arm_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.02" length="${lower_arm_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 -${lower_arm_length/2}" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Changed from spherical to revolute with 3 DOF approximation -->
    <joint name="upper_joint_to_lower_arm_${id}_x" type="revolute">
      <parent link="upper_joint_${id}"/>
      <child link="lower_arm_${id}_x"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
    </joint>
    
    <link name="lower_arm_${id}_x">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>
    
    <joint name="lower_arm_${id}_x_to_y" type="revolute">
      <parent link="lower_arm_${id}_x"/>
      <child link="lower_arm_${id}_y"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
    </joint>
    
    <link name="lower_arm_${id}_y">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>
    
    <joint name="lower_arm_${id}_y_to_z" type="revolute">
      <parent link="lower_arm_${id}_y"/>
      <child link="lower_arm_${id}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
    </joint>

    <link name="lower_joint_${id}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${joint_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="lower_arm_to_joint_${id}" type="fixed">
      <parent link="lower_arm_${id}"/>
      <child link="lower_joint_${id}"/>
      <origin xyz="0 0 -${lower_arm_length}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Platform and end effector -->
  <link name="platform">
    <visual>
      <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <link name="end_effector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.01" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="platform_to_end_effector" type="fixed">
    <parent link="platform"/>
    <child link="end_effector"/>
    <origin xyz="0 0 ${platform_height}" rpy="0 0 0"/>
  </joint>

  <!-- Create three arms at 120-degree intervals -->
  <xacro:upper_arm id="1" angle="0"/>
  <xacro:upper_arm id="2" angle="${2*pi/3}"/>
  <xacro:upper_arm id="3" angle="${4*pi/3}"/>

  <xacro:lower_arm id="1" angle="0"/>
  <xacro:lower_arm id="2" angle="${2*pi/3}"/>
  <xacro:lower_arm id="3" angle="${4*pi/3}"/>

  <!-- Connect lower joints to platform with 3-DOF revolute joints instead of spherical -->
  <joint name="lower_joint_1_to_platform_x" type="revolute">
    <parent link="lower_joint_1"/>
    <child link="platform_joint_1_x"/>
    <origin xyz="${platform_radius} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
  </joint>
  
  <link name="platform_joint_1_x">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint name="platform_joint_1_x_to_y" type="revolute">
    <parent link="platform_joint_1_x"/>
    <child link="platform_joint_1_y"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
  </joint>
  
  <link name="platform_joint_1_y">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint name="platform_joint_1_y_to_platform" type="revolute">
    <parent link="platform_joint_1_y"/>
    <child link="platform"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
  </joint>

  <!-- Define the delta_arm group for MoveIt -->
  <group name="delta_arm">
    <joint name="base_to_upper_arm_1"/>
    <joint name="base_to_upper_arm_2"/>
    <joint name="base_to_upper_arm_3"/>
    <joint name="upper_joint_to_lower_arm_1_x"/>
    <joint name="lower_arm_1_x_to_y"/>
    <joint name="lower_arm_1_y_to_z"/>
    <joint name="upper_joint_to_lower_arm_2_x"/>
    <joint name="lower_arm_2_x_to_y"/>
    <joint name="lower_arm_2_y_to_z"/>
    <joint name="upper_joint_to_lower_arm_3_x"/>
    <joint name="lower_arm_3_x_to_y"/>
    <joint name="lower_arm_3_y_to_z"/>
    <joint name="lower_joint_1_to_platform_x"/>
    <joint name="platform_joint_1_x_to_y"/>
    <joint name="platform_joint_1_y_to_platform"/>
  </group>

  <!-- Define end effector -->
  <end_effector name="delta_ee" parent_link="platform" group="delta_arm"/>

</robot>
