description: Robot arm pick and place scenario
environment:
  type: factory
  size: [10.0, 10.0, 3.0]
  gravity: [0.0, 0.0, -9.81]
  ambient_light: 0.7
robots:
  - id: robot_arm
    type: ur5
    model_file: ../ur5_robot_description/urdf/ur5_robot.urdf.xacro
    position: [0.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    parameters:
      speed: 1.0
      acceleration: 0.5
      gripper_type: parallel
containers:
  - id: basket
    type: basket
    position: [-0.5, 0.0, 0.1]
    dimensions: [0.3, 0.3, 0.2]
conveyors:
  - id: output_conveyor
    type: belt
    position: [0.5, 0.0, 0.1]
    dimensions: [1.0, 0.4, 0.1]
    speed: 0.1
    direction: [0.0, 1.0, 0.0]
