# Pose Estimation Configuration

# Depth parameters
min_depth: 0.1  # Minimum valid depth in meters
max_depth: 5.0  # Maximum valid depth in meters
depth_scale: 0.001  # Scale factor to convert depth values to meters

# Pose estimation parameters
use_ransac: true  # Use RANSAC for pose estimation
ransac_iterations: 100  # Number of RANSAC iterations
ransac_threshold: 0.01  # RANSAC threshold in meters
min_inliers: 10  # Minimum number of inliers for valid pose

# Object models
object_models:
  cube:
    dimensions: [0.05, 0.05, 0.05]
  cylinder:
    radius: 0.025
    height: 0.1
  sphere:
    radius: 0.03
